### ISSUE TITLE
YoloV5-DSConv 后报错，我使用的yolov5 7.0版本

### ISSUE THREAD

**Issue by nortorious** [z1069614715/objectdetection_script#54]
`Traceback (most recent call last):
  File "D:\Github Project\yolov5-7.0\train.py", line 900, in <module>
    main(opt)
  File "D:\Github Project\yolov5-7.0\train.py", line 763, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\Github Project\yolov5-7.0\train.py", line 168, in train
    model = Model(cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "D:\Github Project\yolov5-7.0\models\yolo.py", line 277, in __init__
    self.model, self.save = parse_model(deepcopy(self.yaml), ch=[ch])  # model, savelist
  File "D:\Github Project\yolov5-7.0\models\yolo.py", line 516, in parse_model
    m_ = nn.Sequential(*(m(*args) for _ in range(n))) if n > 1 else m(*args)  # module
  File "D:\Github Project\yolov5-7.0\models\common.py", line 2102, in __init__
    self.m = nn.Sequential(*(Bottleneck_DSConv(c_, c_, shortcut, g, e=1.0) for _ in range(n)))
  File "D:\Github Project\yolov5-7.0\models\common.py", line 2102, in <genexpr>
    self.m = nn.Sequential(*(Bottleneck_DSConv(c_, c_, shortcut, g, e=1.0) for _ in range(n)))
  File "D:\Github Project\yolov5-7.0\models\common.py", line 2090, in __init__
    self.cv1 = DSConv2D(c1, c_, 1, 1)
  File "D:\Github Project\yolov5-7.0\models\common.py", line 2081, in __init__
    self.conv = DSConv(inc, ouc, k, s, p, g,d)
TypeError: __init__() takes from 4 to 7 positional arguments but 8 were given`

**Comment by Mizokuiam** [comment]
Great observation! Let me add some thoughts...
