### ISSUE TITLE
老师您好，我将你复现的项目拉到程序中最后val.py报错了

### ISSUE THREAD

**Issue by wudizuixiaosa** [z1069614715/objectdetection_script#8]
Fusing layers...
Traceback (most recent call last):
  File "val.py", line 399, in <module>
    main(opt)
  File "val.py", line 372, in main
    run(**vars(opt))
  File "C:\Users\hoshi\miniconda3\envs\air\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 141, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data)
  File "I:\AIR\models\common.py", line 492, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, map_location=device)
  File "I:\AIR\models\experimental.py", line 98, in attempt_load
    model.append(ckpt.fuse().eval() if fuse else ckpt.eval())  # fused or un-fused model in eval mode
  File "I:\AIR\models\yolo.py", line 282, in fuse
    m.fuse_repvgg_block()
  File "C:\Users\hoshi\miniconda3\envs\air\lib\site-packages\torch\nn\modules\module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
我拉到的项目不是yolov5原作，而是yoloair里面，你方便帮我看看是个什么原因么

**Comment by wudizuixiaosa** [comment]
训练倒是正常运行的，但是测试就报错了

**Comment by wudizuixiaosa** [comment]
AttributeError: 'RepConv' object has no attribute 'fuse_repvgg_block'
还有一节没复制进去

**Comment by z1069614715** [comment]
请问拉取的是什么内容？

**Comment by wudizuixiaosa** [comment]
> 

gfpn那一个部分

**Comment by z1069614715** [comment]
刚在yolov5 7.0版本进行测试 没问题 yoloair可能要自己debug解决下了

**Comment by wudizuixiaosa** [comment]
> 刚在yolov5 7.0版本进行测试 没问题 yoloair可能要自己debug解决下了

好的那我在研究研究，谢谢您

**Comment by z1069614715** [comment]
看样子是fuse的时候 改了默认的forward导致的
